name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'

    steps:
      - name: Checkout Code Repository
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: pip
          cache-dependency-path: |
            requirements/test.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt

      - name: Tests
        run: pytest
        env:
          ENV: test
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DJANGO_SECRET_KEY: secret
          DJANGO_SITE_ID: 1
          LOG_LEVEL: ERROR
          SENTRY_ENABLED: False
